#######################
# Aurea Central Jervis
#######################
# User guide and documentation can be found at: https://github.com/trilogy-group/central-jervis
# This project is based on https://github.com/samrocketman/jervis

language: shell

# variables are accessible from pipeline
variables:
  - MY_VAR=xyz
  - DEPLOYMENT_TARGET=docker

notifications:
# on_success, on_failure modes
# - always: always send a notification
# - never: never send a notification
# possible notifications options - slack, email
  slack:
    # Configure the Jenkins integration for each channel
    # https://my.slack.com/services/new/jenkins-ci
    #rooms:
     # - channel: "devfactorydev:VkVhrfzU7Lx7dFZWxJtzC4ku:#jervis_builds"
      #  on_success: never
       # on_failure: always

env:
  global:
    - VUEJS_APP_IMAGE_BASE_URL=registry2.swarm.devfactory.com/aurea/central/jervis/spring-boot-vuejs-app
    - DOCKER_HOST=tcp://docker-build.aureacentral.com:2375
    
# Note that you can give a list of agents here.
docker-agents:
  - docker-image: registry2.swarm.devfactory.com/aurea/central/jervis/spring-boot-vuejs-app
    labels: vuejs-app
 
 
# After this, you also need to use these labels somewhere to tell the Jervis server that you want this agent to be used. For that, use the additional_labels section under jenkins as below:

script: 
  - echo "Hello World."
  - echo docker build -t ${VUEJS_APP_IMAGE_BASE_URL} .
  - echo ls -lrt .
  - echo ls -lrt aurea-central-jervis-test/pipelines
  #- echo docker build -t ${VUEJS_APP_IMAGE_BASE_URL}:${GIT_COMMIT} .

jenkins:
  additional_labels: vuejs-app
  pipeline_jenkinsfile: aurea-central-jervis-test/pipelines/SaaS    # Type of pipeline
  collect: []
  
services:
  vuejs-app:                                                                                    #   Identifier for the docker image
    docker_image:                      
     path: .                                                                                    #   Location of the Dockerfile. Default is root folder of the project
     name: registry2.swarm.devfactory.com/aurea/central/jervis/server/spring-boot-vuejs-app    #   Name of the image. Needs to include the registry URL.
                                                                                               #
                                                                                               
branches:
  only:
  - master
  - qa
  - develop
