- name: "Running deployment lifecycle steps"
  include_tasks: load_step_tasks.yml
  loop: "{{ ['stop','uninstall','pre-install','install','post-instal','start'] | intersect(hostvars[inventory_hostname.split('@') | last].jervis.services[inventory_hostname.split('@') | first].keys()) }}"
  loop_control:
    loop_var: step_name
  when: hostvars[inventory_hostname.split('@') | last].jervis.services[inventory_hostname.split('@') | first] is defined
