- name: Log into private registry
  docker_login:
    registry: "{{ docker_registry_url }}"
    username: "{{ docker_registry_username }}"
    password: "{{ docker_registry_password }}"
    docker_host: "tcp://dlb1.aureacentral.com:2375"
  delegate_to: localhost
  delegate_facts: true
  when: docker_registry_username is defined and docker_registry_password is defined
  tags: docker-image-build
  retries: 3

- name: Building docker images
  docker_image:
     path: "../../{{ hostvars[inventory_hostname.split('@') | last].jervis.services[inventory_hostname.split('@') | first].docker_image.path }}"
     name: "{{ hostvars[inventory_hostname.split('@') | last].jervis.services[inventory_hostname.split('@') | first].docker_image.name }}:{{ lookup('env','GIT_COMMIT') }}"
     push: "{{ hostvars[inventory_hostname.split('@') | last].jervis.services[inventory_hostname.split('@') | first].docker_image.push | default('yes')}}"
     dockerfile: "{{ hostvars[inventory_hostname.split('@') | last].jervis.services[inventory_hostname.split('@') | first].docker_image.dockerfile | default(omit)}}"
     docker_host: "{{ hostvars[inventory_hostname.split('@') | last].jervis.services[inventory_hostname.split('@') | first].docker_image.docker_host | default('tcp://dlb1.aureacentral.com:2375')}}"
  delegate_to: localhost
  delegate_facts: true
  when: hostvars[inventory_hostname.split('@') | last].jervis.services[inventory_hostname.split('@') | first] is defined and hostvars[inventory_hostname.split('@') | last].jervis.services[inventory_hostname.split('@') | first].docker_image is defined
  tags: docker-image-build
