---
- name: Selecting next service...
  set_fact:
    container_id: "{{ containers[index|int-1] }}"

- debug:
    msg: "Selected service: {{ container_id }}"

- name: 
  set_fact:
    yml_file: "{{ mode }}/raw/{{ current_service_group.name }}/{{ container_id }}.yml"

- name: removing existing object(s)...
  shell: kubectl delete -f "{{ yml_file }}" --namespace={{ k8s_namespace }}
  when: k8s_mode == 'cli' 
  ignore_errors: yes

- name: removing existing object(s) using api...
  kubernetes:
      certificate_authority_data: "{{ k8s_certificate_authority_data }}"
      api_endpoint: "{{ k8s_api_endpoint }}"
      service_token: "{{ k8s_service_token }}"
      file_reference: "{{ yml_file }}"
      state: absent
  when: k8s_mode == 'api' 
