---
- name: Setting mode and stage to {{ inventory_dir | replace(playbook_dir ~'/','') }}
  set_fact:
    mode: "{{ inventory_dir | replace(playbook_dir ~'/','') }}"
    stage: "{{ inventory_dir | replace(playbook_dir ~'/','') }}"
  when: mode is not defined or stage is not defined
  tags: always

- name: Cleaning up wildcard expression
  set_fact: 
    newservice: "{{ wildcardservice.replace('*','') }}"

- name: Filtering services by wildcard
  set_fact:
    filtered_services: "{{docker_containers[0].service|select('search', newservice)|list}}"

- debug:
    msg: "filtered_services = {{filtered_services}}"

- name: Joinning services list
  set_fact:
    service_containers: "{{service_containers|union(filtered_services)|unique}}"
