---

- name: Expanding port list with bind ip...
  set_fact:
    published_ports: "{{ published_ports | default([]) | union([container_bind_ip ~ ':' ~ item])  }}"
  with_items: "{{ (global_ports | default([])) + (service_group_ports | default([])) + (service_ports | default([])) }}"
  when: container_bind_ip is defined

- name: Expanding port list without bind ip...
  set_fact:
    published_ports: "{{ published_ports | default([]) | union([item])  }}"
  with_items: "{{ (global_ports | default([])) + (service_group_ports | default([])) + (service_ports | default([])) }}"
  when: container_bind_ip is not defined