---
- fail: 
    msg: "Typo error detected. variable name should be 'k8s_raw_yaml'"
  when: k8s_raw_yml is defined
  
- name: Fetching service group level configuration...
  include_vars: "{{ item }}"
  with_first_found: 
    - files: "{{ current_service_group.name }}.yml"
      skip: true

- name: Fetching environment service group level configuration...
  include_vars: "{{ item }}"
  with_first_found: 
    - files: "{{mode}}/group_vars/{{ current_service_group.name }}.yml"
      skip: true
     
- name: Fetching service list for {{mode}} environment...
  set_fact: 
    containers: "{{ current_service_group.services }}"
  when: service is not defined

- name: Evaluating single service override...
  set_fact: 
    service_containers: "{{ service.split(',') }}"
  when: service is defined

- name: Filtering wildcards...
  set_fact:
    wildcard_containers: "{{service_containers|select('search', '\\*')|list}}"
  when: service is defined

- name: Expanding wildcards...
  include_tasks: expand_wildcards.yml
  with_items: "{{ wildcard_containers }}"
  loop_control:
    loop_var: wildcardservice
  when: service is defined

- name: Filtering services per host...
  set_fact: 
    containers: "{{ service_containers }}"
  when: service is defined

- name: Generate configuration and deploy containers...
  include_tasks: create_container.yml
  with_sequence: count={{containers|length}}
  loop_control:
    loop_var: index
  when: perform_deploy is defined and not k8s_raw_yaml 

- name: Deploy RAW Yaml files...
  include_tasks: deploy_raw_yaml.yml
  with_sequence: count={{containers|length}}
  loop_control:
    loop_var: index
  when: perform_deploy is defined and k8s_raw_yaml

- name: Destroy containers...
  include_tasks: destroy_container.yml
  with_sequence: count={{containers|length}}
  loop_control:
    loop_var: index
  when: perform_destroy is defined and not k8s_raw_yaml

- name: Destroy RAW Yaml containers...
  include_tasks: destroy_raw_yaml.yml
  with_sequence: count={{containers|length}}
  loop_control:
    loop_var: index
  when: perform_destroy is defined and k8s_raw_yaml
