- name: "Listing S3 artifact path {{ artifact.src }}"
  aws_s3:
    aws_access_key: "{{ s3_access_key }}"
    aws_secret_key: "{{ s3_secret_key }}"
    bucket: "{{ artifact.src.split('/') | first }}"
    prefix: "{{ artifact.src.split('/') | difference(artifact.src.split('/') | first) | join('/') }}"
    mode: list
  delegate_to: localhost
  register: list_result
  tags: artifact-promote

- name: Evaluating if file or directory
  set_fact:
    artifact_type: "{{ 'file' if list_result.s3_keys | length == 1 and list_result.s3_keys[0] == (artifact.src.split('/') | difference(artifact.src.split('/') | first) | join('/')) else 'directory' }}"
  delegate_to: localhost
  tags: artifact-promote

- name: "Creating temporary file for {{ artifact.src }}"
  tempfile:
    state: "{{ artifact_type }}"
  register: tempfile_result
  delegate_to: localhost
  tags: artifact-promote

- name: "Downloading S3 artifact {{ artifact.src }}"
  aws_s3:
    aws_access_key: "{{ s3_access_key }}"
    aws_secret_key: "{{ s3_secret_key }}"
    bucket: "{{ artifact.src.split('/') | first }}"
    object: "{{ object_key }}"
    mode: get
    dest: "{{ tempfile_result.path }}"
  delegate_to: localhost
  loop: "{{ list_result.s3_keys }}"
  loop_control:
    loop_var: object_key
  tags: artifact-promote

- name: Listing files to upload...
  find:
    paths: "{{ tempfile_result.path }}"
    recurse: yes
  delegate_to: localhost
  register: list_result

- name: Evaluating if file or directory
  set_fact:
    file_artifact: true
    list_result:
      matched: 1
      files:
        - path: "{{ tempfile_result.path }}"
  delegate_to: localhost
  when: not list_result.matched

- name: Promoting files to S3
  aws_s3:
    aws_access_key: "{{ s3_access_key }}"
    aws_secret_key: "{{ s3_secret_key }}"
    bucket: "{{ artifact.target.split('/') | first }}"
    object: "{{ artifact.target.split('/') | difference(artifact.target.split('/') | first) | join('/') ~ ( (file_artifact is defined | ternary('', artifact_file.path.split(tempfile_result.path) | last ))) }}"
    src: "{{ artifact_file.path }}"
    mode: put
  loop: "{{ list_result.files }}"
  loop_control:
    loop_var: artifact_file
  delegate_to: localhost