- name: "Testing if we will overwrite {{ artifact.target }}"
  uri:
    url: "https://nexus.devfactory.com/repository/{{ artifact.target }}"
    user: "{{ nexus_username }}"
    password: "{{ nexus_password }}"
    method: HEAD
    force_basic_auth: yes
    status_code: 404
  delegate_to: localhost
  when: not (artifact.overwrite | default(false))
  tags: artifact-promote

- name: "Creating temporary file for {{ artifact.src }}"
  tempfile:
  register: tempfile_result
  delegate_to: localhost
  tags: artifact-promote

- name: "Downloading Nexus artifact {{ artifact.src }}"
  get_url:
    url:  "https://nexus.devfactory.com/repository/{{ artifact.src }}"
    url_username: "{{ nexus_username }}"
    url_password: "{{ nexus_password }}"
    dest: "{{ tempfile_result.path }}"
    force: yes
  delegate_to: localhost
  tags: artifact-promote
    
- name: "Publishing promoted Nexus artifact {{ artifact.target }}"
  shell: "curl -k -X PUT -v --upload-file {{ tempfile_result.path }} -u '{{ nexus_username }}:{{ nexus_password }}' 'https://nexus.devfactory.com/repository/{{ artifact.target }}'"
  delegate_to: localhost
  tags: artifact-promote