- name: Testing if we will overwrite something we shouldn't
  uri:
    url: "https://nexus.devfactory.com/repository/{{ artifact.target }}"
    user: "{{ nexus_username }}"
    password: "{{ nexus_password }}"
    method: HEAD
    force_basic_auth: yes
    status_code: 404
  delegate_to: localhost
  loop: "{{ (hostvars[inventory_hostname.split('@') | last].jervis.services[inventory_hostname.split('@') | first].nexus | default({ 'publish': {} })).publish[environment_name] | default([])}}"
  loop_control:
    loop_var: artifact
  when: hostvars[inventory_hostname.split('@') | last].jervis.services[inventory_hostname.split('@') | first] is defined and hostvars[inventory_hostname.split('@') | last].jervis.services[inventory_hostname.split('@') | first].nexus is defined and not (artifact.overwrite | default(false))

- name: Publishing Nexus Artifacts
  shell: "curl -k -X PUT -v --upload-file {{ lookup('env','WORKSPACE') ~ '/' ~ artifact.src }} -u '{{ nexus_username }}:{{ nexus_password }}' 'https://nexus.devfactory.com/repository/{{ artifact.target }}'"
  delegate_to: localhost
  loop: "{{ (hostvars[inventory_hostname.split('@') | last].jervis.services[inventory_hostname.split('@') | first].nexus | default({ 'publish': {} })).publish[environment_name] | default([])}}"
  loop_control:
    loop_var: artifact
  when: hostvars[inventory_hostname.split('@') | last].jervis.services[inventory_hostname.split('@') | first] is defined and hostvars[inventory_hostname.split('@') | last].jervis.services[inventory_hostname.split('@') | first].nexus is defined
