- name: Publishing S3 Artifacts
  s3_sync:
    aws_access_key: "{{ s3_access_key }}"
    aws_secret_key: "{{ s3_secret_key }}"
    bucket: "{{ artifact.target.split('/') | first }}"
    key_prefix: "{{ artifact.target.split('/') | difference(artifact.target.split('/') | first) | join('/') }}"
    file_root: "{{ lookup('env','WORKSPACE') ~ '/' ~ artifact.src }}"
    region: "{{ artifact.region | default('us-east-1') }}"
  delegate_to: localhost
  loop: "{{ (hostvars[inventory_hostname.split('@') | last].jervis.services[inventory_hostname.split('@') | first].s3 | default({ 'publish': {} })).publish[environment_name] | default([]) }}"
  loop_control:
    loop_var: artifact