- name: "Adding dynamic instances to inventory"
  add_host:
    name: "{{ dynamic_instance.name }}"
    ansible_connection: "{{ dynamic_instance.ansible_connection | default(omit) }}"
    ansible_winrm_server_cert_validation: "{{ dynamic_instance.ansible_winrm_server_cert_validation | default(omit) }}"
    ansible_docker_extra_args: "{{ dynamic_instance.ansible_docker_extra_args | default(omit) }}"
    ansible_host: "{{ dynamic_instance.ansible_host | default(omit) }}"
    ansible_user: "{{ dynamic_instance.ansible_user | default(omit) }}"
    ansible_password: "{{ dynamic_instance.ansible_password | default(omit) }}"
    groups: "{{ dynamic_instance.groups }}"
    environment_name: "{{ dynamic_instance.environment_name }}"
  loop: "{{ hostvars.values() | selectattr('dynamic_inventory','defined') | map(attribute='dynamic_inventory') | flatten }}"
  loop_control:
    loop_var: dynamic_instance
    label: "{{ dynamic_instance.name }}"
  changed_when: false
  tags: always
