- name: "Adding dynamic instances to inventory"
  add_host:
    name: "{{ dynamic_instance.name }}"
    docker_host: "{{ dynamic_instance.docker_host | default(omit) }}"
    groups: "{{ dynamic_instance.groups }}"
    environment_name: "{{ dynamic_instance.environment_name }}"
    ansible_connection: "{{ dynamic_instance.ansible_connection | default(omit) }}"
    ansible_winrm_server_cert_validation: "{{ dynamic_instance.ansible_winrm_server_cert_validation | default(omit) }}"
    ansible_docker_extra_args: "{{ dynamic_instance.ansible_docker_extra_args | default(omit) }}"
    ansible_host: "{{ dynamic_instance.ansible_host | default(omit) }}"
    ansible_user: "{{ dynamic_instance.ansible_user | default(omit) }}"
    ansible_password: "{{ dynamic_instance.ansible_password | default(omit) }}"
    ansible_port: "{{ dynamic_instance.ansible_port | default(omit) }}"
    ansible_ssh_pass: "{{ dynamic_instance.ansible_ssh_pass | default(omit) }}"
    ansible_ssh_private_key_file: "{{ dynamic_instance.ansible_ssh_private_key_file | default(omit) }}"
    ansible_ssh_common_args: "{{ dynamic_instance.ansible_ssh_common_args | default(omit) }}"
    ansible_sftp_extra_args: "{{ dynamic_instance.ansible_sftp_extra_args | default(omit) }}"
    ansible_scp_extra_args: "{{ dynamic_instance.ansible_scp_extra_args | default(omit) }}"
    ansible_ssh_extra_args: "{{ dynamic_instance.ansible_ssh_extra_args | default(omit) }}"
    ansible_ssh_pipelining: "{{ dynamic_instance.ansible_ssh_pipelining | default(omit) }}"
    ansible_ssh_executable: "{{ dynamic_instance.ansible_ssh_executable | default(omit) }}"
    ansible_become: "{{ dynamic_instance.ansible_become | default(omit) }}"
    ansible_become_method: "{{ dynamic_instance.ansible_become_method | default(omit) }}"
    ansible_become_user: "{{ dynamic_instance.ansible_become_user | default(omit) }}"
    ansible_become_pass: "{{ dynamic_instance.ansible_become_pass | default(omit) }}"
    ansible_become_exe: "{{ dynamic_instance.ansible_become_exe | default(omit) }}"
    ansible_become_flags: "{{ dynamic_instance.ansible_become_flags | default(omit) }}"
    ansible_shell_type: "{{ dynamic_instance.ansible_shell_type | default(omit) }}"
    ansible_python_interpreter: "{{ dynamic_instance.ansible_python_interpreter | default(omit) }}"
    ansible_shell_executable: "{{ dynamic_instance.ansible_shell_executable | default(omit) }}"
    ansible_winrm_scheme: "{{ dynamic_instance.ansible_winrm_scheme | default(omit) }}"
    ansible_winrm_path: "{{ dynamic_instance.ansible_winrm_path | default(omit) }}"
    ansible_winrm_realm: "{{ dynamic_instance.ansible_winrm_realm | default(omit) }}"
    ansible_winrm_transport: "{{ dynamic_instance.ansible_winrm_transport | default(omit) }}"
    ansible_winrm_operation_timeout_sec: "{{ dynamic_instance.ansible_winrm_operation_timeout_sec | default(omit) }}"
    ansible_winrm_read_timeout_sec: "{{ dynamic_instance.ansible_winrm_read_timeout_sec | default(omit) }}"
    ansible_winrm_message_encryption: "{{ dynamic_instance.ansible_winrm_message_encryption | default(omit) }}"
    ansible_winrm_ca_trust_path: "{{ dynamic_instance.ansible_winrm_ca_trust_path | default(omit) }}"
    ansible_winrm_send_cbt: "{{ dynamic_instance.ansible_winrm_send_cbt | default(omit) }}"
    ansible_winrm_cert_pem: "{{ dynamic_instance.ansible_winrm_cert_pem | default(omit) }}"
    ansible_winrm_cert_key_pem: "{{ dynamic_instance.ansible_winrm_cert_key_pem | default(omit) }}"
    ansible_winrm_kinit_mode: "{{ dynamic_instance.ansible_winrm_kinit_mode | default(omit) }}"
    ansible_winrm_kinit_cmd: "{{ dynamic_instance.ansible_winrm_kinit_cmd | default(omit) }}"
    ansible_winrm_service: "{{ dynamic_instance.ansible_winrm_service | default(omit) }}"
    ansible_winrm_kerberos_delegation: "{{ dynamic_instance.ansible_winrm_kerberos_delegation | default(omit) }}"
    ansible_winrm_kerberos_hostname_override: "{{ dynamic_instance.ansible_winrm_kerberos_hostname_override | default(omit) }}"
    ansible_winrm_credssp_disable_tlsv1_2: "{{ dynamic_instance.ansible_winrm_credssp_disable_tlsv1_2 | default(omit) }}"
    version_tag: "{{ version_tag | default(omit) }}"
  loop: "{{ hostvars.values() | selectattr('dynamic_inventory','defined') | map(attribute='dynamic_inventory') | flatten }}"
  loop_control:
    loop_var: dynamic_instance
    label: "{{ dynamic_instance.name }}"
  changed_when: false
  tags: always
