
- name: "Mapping Docker Host services"
  set_fact:
    dynamic_inventory: "{{ dynamic_inventory + 
                          ([ hostvars[inventory_hostname] 
                          | combine({
                                      'name': service.name ~ '@'  ~ inventory_hostname,
                                      'service': jervis.services[service.name],
                                      'groups': group_names + ['docker-service'],
                                      'ansible_connection': 'docker'
                                    }) 
                          ] | list)
                        }}"
  loop: "{{ services }}"
  loop_control:
    loop_var: service
    label: "{{ service.name }}"
  connection: local
  tags: 
    - docker-image-build
    - docker-service-deploy