- name: "Searching Jervis Configuration"
  include_vars:
    file: "{{ lookup('env', 'WORKSPACE') }}/{{ lookup('env', 'JERVIS_YAML') }}"
    name: jervis
  delegate_to: localhost
- name: Pausing local deployments
  pause:
    seconds: 1
    prompt: "Ansible detected you are not running in a CICD environment like Jenkins. While it's possible to run Jervis Ansible outside CICD,
    you must mimic it's environment and provide general use environment variables: GIT_COMMIT CHANGE_TARGE BRANCH_NAME, IS_PR_BUILD.
    We will default to dev and random values and resume your deploy in a couple of seconds. To dismiss this message, setup your environment properly | comment"
  when: lookup('env','BRANCH_NAME') == ''
  register: agent_check_result
- name: "Defaulting parameters"
  set_fact:
    BRANCH_NAME: feature
    CHANGE_TARGET: feature
    GIT_COMMIT: "{{ 99999999 | random | to_uuid }}"
    environment_name: dev
  when: lookup('env','BRANCH_NAME') == ''
- name: "Selecting target environment"
  set_fact:
    environment_name: "{{ branch_environment_map[ branch_environment_key ][ branch_environment_key ] | default('dev') }}"
  when: lookup('env','BRANCH_NAME') != '' and environment_name is not defined
- name: "Evaluating if trigger is Pull Request"
  set_fact:
    environment_name: "{{ branch_environment_map[ branch_environment_key ][ lookup('env','CHANGE_TARGET') | default(environment_name, true) | lower] | default('dev') }}"
  when: lookup('env','IS_PR_BUILD') != '' and lookup('env','IS_PR_BUILD') | bool
- name: "Fetching version tags..."
  shell: 'git describe --tags --abbrev=0 || echo $GIT_COMMIT | cut -c1-7'
  args:
    chdir: "{{ lookup('env', 'WORKSPACE') }}"
  register: version_tag_describe_result
  delegate_to: localhost
  check_mode: false
- name: "Converting version"
  set_fact:
    version_tag: "{{ version_tag_describe_result.stdout }}"
    tag_suffix: "{{ branch_environment_map[ branch_environment_key ].tag_suffix | default('-UNSTABLE') }}"
    promote_tag_suffix: "{{ branch_environment_map[ branch_environment_key ].promote_tag_suffix | default('-DEVEL') }}"
  delegate_to: localhost
- name: "Using git hash for development"
  set_fact:
    version_tag: "{{ lookup('env', 'GIT_COMMIT')[:7] }}"
  delegate_to: localhost
  when: hostvars['localhost'].environment_name == 'dev'
