- name: "Searching Jervis Configuration"
  include_vars:
    file: "{{ possible_jervis_filename }}"
    name: jervis
  with_first_found:
    - "{{ lookup('env', 'WORKSPACE') }}/.jervis.yml"
    - "{{ lookup('env', 'WORKSPACE') }}/.jervis.yaml"
    - "{{ lookup('env', 'WORKSPACE') }}/.travis.yml"
    - "{{ lookup('env', 'WORKSPACE') }}/.travis.yaml"
    - ".jervis.yml"
    - ".jervis.yaml"
    - ".travis.yml"
    - ".travis.yaml"
  loop_control:
    loop_var: possible_jervis_filename
  connection: local
- name: Pausing local deployments
  pause:
    seconds: 5
    prompt: "Ansible detected you are not running in a CICD environment like Jenkins. While it's possible to run Jervis Ansible outside CICD, 
    you must mimic it's environment and provide general use environment variables: GIT_COMMIT CHANGE_TARGE BRANCH_NAME, IS_PR_BUILD. 
    We will default to dev and random values and resume your deploy in a couple of seconds. To dismiss this message, setup your environment properly | comment"
  when: lookup('env','BRANCH_NAME') == '' or lookup('env','CHANGE_TARGET') == ''  or lookup('env','GIT_COMMIT') == '' 
  register: agent_check_result
- name: "Defaulting parameters"
  set_fact:
    BRANCH_NAME: feature
    CHANGE_TARGET: feature
    GIT_COMMIT: "{{ 99999999 | random | to_uuid }}"
    environment_name: dev
  when: agent_check_result is changed
- name: "Selecting target environment"
  set_fact:
    environment_name: "{{ branch_environment_map[lookup('env','BRANCH_NAME') | default('feature') | lower][ lookup('env',(lookup('env','IS_PR_BUILD') | ternary('CHANGE_TARGET','BRANCH_NAME')))]}}"
  delegate_to: "{{ inventory_instance }}"
  loop: "{{ groups['all'] }}"
  loop_control:
    loop_var: inventory_instance
    label: "{{ inventory_instance }}"
  when: agent_check_result is skipped