kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  namespace: "{{ namespace }}"
  name: "{{ service_vars.container_hostname }}"
  labels:
    app_name: "{{ service_vars.container_hostname }}"
  annotations:
#    nginx.ingress.kubernates.io/rewrite-target: /
#    ingress.kubernates.io/rewrite-target: /
#    nginx.ingress.kubernates.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: "nonprod-public"
spec:
