kind: Service
apiVersion: v1
metadata:
  namespace: "{{ namespace }}"
  name: "{{ service_vars.container_hostname }}"
  labels:
    app_name: "{{ service_vars.container_hostname }}"
spec:
  type: ClusterIP
  selector:
    app_name: "{{ service_vars.container_hostname }}"

