kind: Service
apiVersion: v1
metadata:
  namespace: "{{ namespace }}"
  name: "{{ container_hostname }}"
  labels:
    app_name: "{{ container_hostname }}"
spec:
  type: ClusterIP
  selector:
    app_name: "{{ container_hostname }}"

