---
- name: Aurea Central Jervis Preflight
  vars:
    branch_environment_map:
      feature: 
        feature: dev
        develop: dev
      develop:
        develop: regression
        qa: qa
      qa:
        qa: qa
        release: qa
      release:
        release: staging
        master: staging
      master: 
        master: prod
  hosts: 
    - all
  tags: always
  gather_facts: no
  roles:
    - agent-preflight
    
- name: Aurea Central Jervis EC2 Hosts
  serial: 100%
  hosts: 
    - ec2
  tags: always
  vars:
    dynamic_inventory: []
  gather_facts: no
  roles:
    - ec2-host

- name: Aurea Central Jervis Docker Hosts
  serial: 100%
  hosts: 
    - docker-host
  vars:
    dynamic_inventory: []
  gather_facts: no
  tags: always
  roles:
    - docker-host
    
- name: Aurea Central Jervis Build Inventory
  hosts: 
    - localhost
  tags: always
  gather_facts: no
  roles:
    - agent-build-inventory
  
- name: Aurea Central Jervis Docker Images
  strategy: free
  hosts: 
    - docker-service
  tags: docker-image-build
  gather_facts: no
  roles:
    - docker-image-build
  
- name: Aurea Central Jervis Docker Containers
  strategy: free
  hosts: 
    - docker-service
  tags: docker-service-deploy
  gather_facts: no
  roles:
    - container-update

- name: Aurea Central Jervis Services
  strategy: free
  hosts: 
    - ec2-service
    - docker-service
  tags: 
    - ec2-service-deploy
    - docker-service-deploy
  gather_facts: no
  roles:
    - service-deploy


- name: Aurea Central Jervis Health Checks
  strategy: free
  hosts: 
    - docker-service
    - ec2-service
  tags: run-health-checks
  vars:    
    - jervis: "{{ hostvars['localhost'].jervis }}"
  gather_facts: no
  roles:
    - run-health-checks

- name: Aurea Central Jervis Smoke Tests
  strategy: free
  hosts: 
    - docker-service
    - ec2-service
  tags: run-smoke-tests
  vars:    
    - jervis: "{{ hostvars['localhost'].jervis }}"
  gather_facts: no
  roles:
    - run-smoke-tests

- name: Aurea Central Jervis Regression Tests
  strategy: free
  hosts: 
    - docker-service
    - ec2-service
  tags: run-regression-tests
  vars:    
    - jervis: "{{ hostvars['localhost'].jervis }}"
  gather_facts: no
  roles:
    - run-regression-tests    

- name: Aurea Central Jervis Performance Tests
  strategy: free
  hosts: 
    - docker-service
    - ec2-service
  tags: run-performance-tests
  vars:    
    - jervis: "{{ hostvars['localhost'].jervis }}"
  gather_facts: no
  roles:
    - run-performance-tests
    
- name: Aurea Central Jervis Load Tests
  strategy: free
  hosts: 
    - docker-service
    - ec2-service
  tags: run-load-tests
  vars:    
    - jervis: "{{ hostvars['localhost'].jervis }}"
  gather_facts: no
  roles:
    - run-load-tests    

- name: Aurea Central Jervis Security Tests
  strategy: free
  hosts: 
    - docker-service
    - ec2-service
  tags: run-security-tests
  vars:    
    - jervis: "{{ hostvars['localhost'].jervis }}"
  gather_facts: no
  roles:
    - run-security-tests    

- name: Aurea Central Jervis Promote Packages
  strategy: free
  hosts: 
    - docker-service
    - ec2-service
  tags: promote-packages
  vars:    
    - jervis: "{{ hostvars['localhost'].jervis }}"
  gather_facts: no
  roles:
    - promote-packages    

- name: Aurea Central Jervis Send Notification
  strategy: free
  hosts: 
    - docker-service
    - ec2-service
  tags: send-notification
  vars:    
    - jervis: "{{ hostvars['localhost'].jervis }}"
  gather_facts: no
  roles:
    - send-notification    

- name: Aurea Central Jervis K8s Service Deploy
  strategy: free
  hosts:
    - k8s-service
  tags:
    - k8s-service-deploy
  vars:
    - jervis: "{{ hostvars['localhost'].jervis }}"
  gather_facts: no
  roles:
    - k8s-service-deploy
