---
- name: Aurea Central Jervis Preflight
  vars:
    branch_environment_map:
      feature: 
        feature: dev
        develop: dev
      develop:
        develop: regression
        qa: qa
      qa:
        qa: qa
        release: qa
      release:
        release: staging
        master: staging
      master: prod
  hosts: 
    - all
  tags: always
  gather_facts: no
  roles:
    - agent-preflight
    
- name: Aurea Central Jervis EC2 Hosts
  serial: 100%
  hosts: 
    - ec2
  tags: ec2-instance
  vars:
    dynamic_inventory: []
  gather_facts: no
  roles:
    - ec2-instance

- name: Aurea Central Jervis Docker Hosts
  serial: 100%
  hosts: 
    - docker-host
  vars:
    dynamic_inventory: []
  gather_facts: no
  roles:
    - docker-host
    
- name: Aurea Central Jervis Build Inventory
  hosts: 
    - localhost
  tags: always
  gather_facts: no
  roles:
    - agent-build-inventory

- name: Aurea Central Jervis EC2 Services
  strategy: free
  hosts: 
    - ec2-service
  tags: ec2-service-deploy
  vars:    
    - jervis: "{{ hostvars['localhost'].jervis }}"
  gather_facts: no
  roles:
    - ec2-service-deploy
  
- name: Aurea Central Jervis Docker Images
  strategy: free
  hosts: 
    - docker-service
  tags: docker-image-build
  vars:    
    - jervis: "{{ hostvars['localhost'].jervis }}"
  gather_facts: no
  roles:
    - docker-image-build
  
- name: Aurea Central Jervis Docker Services
  strategy: free
  hosts: 
    - docker-service
  tags: docker-service-deploy
  vars:    
    - jervis: "{{ hostvars['localhost'].jervis }}"
  gather_facts: no
  roles:
    - docker-service-deploy

- name: Aurea Central Jervis Health Checks
  strategy: free
  hosts: 
    - docker-host
  tags: run-health-checks
  vars:    
    - jervis: "{{ hostvars['localhost'].jervis }}"
  gather_facts: no
  roles:
    - run-health-checks

- name: Aurea Central Jervis Smoke Tests
  strategy: free
  hosts: 
    - docker-host
  tags: run-smoke-tests
  vars:    
    - jervis: "{{ hostvars['localhost'].jervis }}"
  gather_facts: no
  roles:
    - run-smoke-tests

- name: Aurea Central Jervis Regression Tests
  strategy: free
  hosts: 
    - docker-host
  tags: run-regression-tests
  vars:    
    - jervis: "{{ hostvars['localhost'].jervis }}"
  gather_facts: no
  roles:
    - run-regression-tests    

- name: Aurea Central Jervis Performance Tests
  strategy: free
  hosts: 
    - docker-host
  tags: run-performance-tests
  vars:    
    - jervis: "{{ hostvars['localhost'].jervis }}"
  gather_facts: no
  roles:
    - run-performance-tests
    
- name: Aurea Central Jervis Load Tests
  strategy: free
  hosts: 
    - docker-host
  tags: run-load-tests
  vars:    
    - jervis: "{{ hostvars['localhost'].jervis }}"
  gather_facts: no
  roles:
    - run-load-tests    

- name: Aurea Central Jervis Security Tests
  strategy: free
  hosts: 
    - docker-host
  tags: run-security-tests
  vars:    
    - jervis: "{{ hostvars['localhost'].jervis }}"
  gather_facts: no
  roles:
    - run-security-tests    
