---
- name: Aurea Central Jervis Preflight
  vars:
    branch_environment_map:
      feature: 
        feature: dev
        develop: dev
      develop:
        develop: regression
        qa: regression
      qa:
        qa: qa
        release: qa
      release:
        release: staging
        master: staging
      master: 
        master: prod
  hosts: 
    - all
  tags: always
  gather_facts: no
  roles:
    - agent-preflight
    
- name: Aurea Central Jervis EC2 Hosts
  serial: 100%
  hosts: 
    - ec2
  tags: always
  vars:
    dynamic_inventory: []
  gather_facts: no
  roles:
    - ec2-host

- name: Aurea Central Jervis Docker Hosts
  serial: 100%
  hosts: 
    - docker-host
  vars:
    dynamic_inventory: []
  gather_facts: no
  tags: always
  roles:
    - docker-host

- name: Checking if we are going to destroy vmware...
  tasks:
    - name: Set perform_destroy...
      set_fact:
        perform_destroy: true
  hosts:
    - vmware-group
  tags:
    - destroy

- name: Aurea Central Jervis VMWare Deploy
  strategy: free
  hosts:
    - vmware-group
  tags:
    - vmware-create
  vars:
    - dynamic_inventory: []
    - jervis: "{{ hostvars['localhost'].jervis }}"
  gather_facts: no
  roles:
    - vmware-group
    
- name: Aurea Central Jervis Build Inventory
  hosts: 
    - localhost
  tags: always
  gather_facts: no
  roles:
    - agent-build-inventory
  
- name: Aurea Central Jervis Docker Images
  strategy: free
  hosts: 
    - docker-service
  tags: docker-image-build
  gather_facts: no
  roles:
    - docker-image-build
  
- name: Aurea Central Jervis Docker Containers
  strategy: free
  hosts: 
    - docker-service
  tags: docker-service-deploy
  gather_facts: no
  roles:
    - container-update

- name: Aurea Central Jervis VMWare deploy
  strategy: free
  hosts: 
    - vmware-service
  tags:
    - vmware-service-deploy
  gather_facts: no
  roles:
    - service-deploy

- name: Aurea Central Jervis Services
  strategy: free
  hosts:
    - ec2-service
    - docker-service
  tags:
    - ec2-service-deploy
    - docker-service-deploy
  gather_facts: no
  roles:
    - service-deploy

- name: Aurea Central Jervis Health Checks
  strategy: free
  hosts: 
    - docker-service
    - ec2-service
  tags: health-check
  vars:    
    step_name: health-check
  gather_facts: no
  roles:
    - dynamic-task

- name: Aurea Central Jervis Smoke Tests
  strategy: free
  hosts: 
    - docker-service
    - ec2-service
  tags: smoke-test
  vars:    
    step_name: smoke-test
  gather_facts: no
  roles:
    - dynamic-task

- name: Aurea Central Jervis Regression Tests
  strategy: free
  hosts: 
    - docker-service
    - ec2-service
  tags: regression-test
  vars:    
    step_name: regression-test
  gather_facts: no
  roles:
    - dynamic-task

- name: Aurea Central Jervis Performance Tests
  strategy: free
  hosts: 
    - docker-service
    - ec2-service
  tags: performance-test
  vars:    
    step_name: performance-test
  gather_facts: no
  roles:
    - dynamic-task

- name: Aurea Central Jervis Load Tests
  strategy: free
  hosts: 
    - docker-service
    - ec2-service
  tags: load-test
  vars:    
    step_name: load-test
  gather_facts: no
  roles:
    - dynamic-task

- name: Aurea Central Jervis Security Tests
  strategy: free
  hosts: 
    - docker-service
    - ec2-service
  tags: security-test
  vars:    
    step_name: security-test
  gather_facts: no
  roles:
    - dynamic-task 

- name: Aurea Central Jervis Promote Packages
  strategy: free
  hosts: 
    - docker-service
    - ec2-service
  tags: promote-packages
  vars:    
    - jervis: "{{ hostvars['localhost'].jervis }}"
  gather_facts: no
  roles:
    - promote-packages    

- name: Aurea Central Jervis Send Notification
  strategy: free
  hosts: 
    - docker-service
    - ec2-service
  tags: send-notification
  vars:    
    - jervis: "{{ hostvars['localhost'].jervis }}"
  gather_facts: no
  roles:
    - send-notification    

- name: Checking if we are going to destroy...
  tasks:
    - name: Set perform_destroy...
      set_fact:
        perform_destroy: true
  hosts:
    - k8s-group
  tags:
    - destroy

- name: Aurea Central Jervis K8s Service Deploy
  strategy: free
  hosts:
    - k8s-group
  tags:
    - k8s-deploy
  vars:
    - jervis: "{{ hostvars['localhost'].jervis }}"
  gather_facts: no
  roles:
    - k8s-group
