---

- name: Set container_image_tag_backward if defined (backward compatibility)
  set_fact:
    container_image_tag_backward: "{{ container_image_tag }}"
  when: container_image_tag is defined

- name: Set container_image_tag if not defined (backward compatibility)
  set_fact:
    container_image_tag: "{{ container_image_tag_default }}"
  when: container_image_tag is not defined

- name: Create kubernetes deployment
  include_tasks: create_primitive.yml
  vars:
    type: 'deployment'
    service_name: "{{ item.key }}"
    service_vars_current: "{{ item.value.vars | default( {} ) }}"
    definition: "{{ item.value.definition }}"
  with_dict: "{{ definitions }}"
