---
- name: Create kubernetes deployment
  include_tasks: create_primitive.yml
  vars:
    type: 'deployment'
    service_name: "{{ item.key }}"
    service_vars_current: "{{ item.vars | default( {} ) }}"
    definition: "{{ item.value.definition }}"
  with_dict: "{{ definitions }}"
