---
- name: Set default container_image_tag if not defined
  set_fact:
    container_image_tag: "{{ hostvars['localhost'].version_tag }}{{ hostvars['localhost'].tag_suffix }}"
  when: container_image_tag is not defined

- name: Show kubernetes definitions
  debug: var=definitions

- name: Create kubernetes deployment
  include_tasks: create_primitive.yml
  vars:
    type: 'deployment'
    service_name: "{{ item.key }}"
    service_vars_current: "{{ item.value.vars | default( {} ) }}"
    definition: "{{ item.value.definition }}"
  loop: "{{ definitions |dict2items }}"
