---
- name: Create kubernetes ingress
  include_tasks: create_primitive.yml
  vars:
    type: 'ingress'
    service_name: "{{ item.key }}"
    service_vars: "{{ item.vars | default( {} ) }}"
    definition: "{{ item.value.definition }}"
  with_dict: "{{ definitions }}"
