---
- name: Check if docker image was built
  fail:
    msg: |
      Docker image was not built, though you have defined services in .jervis.yml file.
      Have you added proper service hostname in k8s-group inventory?
  when: hostvars['localhost'].docker_image_build_result is not defined and jervis.services is defined
  delegate_to: localhost
  run_once: true

- name: Set container_image_tag if not defined
  set_fact:
    container_image_tag: "{{ hostvars['localhost'].version_tag }}{{ hostvars['localhost'].tag_suffix }}"
  when: container_image_tag is not defined

- name: Run k8s object deployment tasks
  include_tasks: object.yml
  when: inventory_hostname == 'k8s-object-host'

- name: Run k8s services tasks
  include_tasks: service.yml
  when: inventory_hostname == 'k8s-service-host'

- name: Run k8s ingress tasks
  include_tasks: ingress.yml
  when: inventory_hostname == 'k8s-ingress-host'

- name: Run k8s deployments tasks
  include_tasks: deployment.yml
  when: inventory_hostname == 'k8s-deployment-host'
