---
- name: Output inventory_hostname
  debug: 
    msg: "{{ inventory_hostname }}"
  
- name: Run k8s object deployment tasks
  include_tasks: object.yml
  when: inventory_hostname == 'k8s-object-host'

- name: Run k8s services tasks
  include_tasks: service.yml
  when: inventory_hostname == 'k8s-service-host'

- name: Run k8s ingress tasks
  include_tasks: ingress.yml
  when: inventory_hostname == 'k8s-ingress-host'

- name: Run k8s deployments tasks
  include_tasks: deployment.yml
  when: inventory_hostname == 'k8s-deployment-host'

- name: Run k8s statefulsets tasks
  include_tasks: statefulset.yml
  when: inventory_hostname == 'k8s-statefulset-host'