---
- name: Create kubernetes services
  include_tasks: create_primitive.yml
  vars:
    type: 'service'
    service_name: "{{ item.key }}"
    service_vars_current: "{{ item.value.vars | default( {} ) }}"
    definition: "{{ item.value.definition }}"
  with_dict: "{{ hostvars[inventory_hostname.split('@') | last].definitions }}"
